version: "3.9"
services:

  camunda:
    image: lwluc/camunda-open-apm-demo:camunda
    build: ./camunda-platform-engine
    mem_limit: 512M
    depends_on:
        - external-service
    environment:
      - INSPECTIT_SERVICE_NAME=camunda
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_ENABLED=true
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    entrypoint: ["sh", "-c","
        ./dockerize -wait=tcp://external-service:7788 -timeout=360s -- &&
        sh /usr/app/entrypoint.sh"]
    ports:
      - 7777:7777
    
  external-service:
    image: lwluc/camunda-open-apm-demo:external-service
    build: ./external-service
    mem_limit: 512M
    environment:
      - INSPECTIT_SERVICE_NAME=external-service
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_ENABLED=true
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    entrypoint: [ "sh", "/usr/app/entrypoint.sh"]
    ports:
      - 7788:7788
  
  micronaut-client:
    image: lwluc/camunda-open-apm-demo:micronaut-client
    build: ./micronaut-client
    mem_limit: 512M
    depends_on:
        - camunda
        - external-service
    environment:
      - INSPECTIT_SERVICE_NAME=micronaut-client
      - INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_ENABLED=false
      - INSPECTIT_EXPORTERS_METRICS_INFLUX_URL=http://influxdb:8086
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_ENABLED=true
      - INSPECTIT_EXPORTERS_TRACING_JAEGER_URL=http://jaeger:14268/api/traces
    entrypoint: ["sh", "-c","
        ./dockerize -wait=tcp://camunda:7777 -timeout=360s -- &&
        sh /usr/app/entrypoint.sh"]
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    mem_limit: 512M
    volumes:
      - ./monitoring/influx:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
    
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268
      - 16686

  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=TRUE
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_INSTALL_PLUGINS=https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/download/v4.0.2/novatec-sdg-panel.zip;novatec-sdg-panel
    volumes:
      - ./monitoring/grafana/provisioning/influxdb:/usr/share/grafana/custom/
    ports:
      - 3001:3000