version: "3.9"
services:

  camunda:
    image: lwluc/camunda-open-apm-demo:camunda
    build: ./camunda-platform-engine
    depends_on:
      - otel-collector
      - external-service
    environment:
      - JAVA_AGENT_ENABLED=true
      - OTEL_SERVICE_NAME=camunda
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    entrypoint: ["sh", "-c","
        ./dockerize -wait=tcp://external-service:7788 -timeout=360s -- &&
        sh /usr/app/entrypoint.sh"]
    ports:
      - "7777:7777"
    
  external-service:
    image: lwluc/camunda-open-apm-demo:external-service
    build: ./external-service
    depends_on:
      - otel-collector
    environment:
      - JAVA_AGENT_ENABLED=true
      - OTEL_SERVICE_NAME=external-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    entrypoint: [ "sh", "/usr/app/entrypoint.sh"]
    ports:
      - "7788:7788"
  
  micronaut-client:
    image: lwluc/camunda-open-apm-demo:micronaut-client
    build: ./micronaut-client
    depends_on:
      - otel-collector
      - camunda
      - external-service
    environment:
      - JAVA_AGENT_ENABLED=true
      - OTEL_SERVICE_NAME=micronaut-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    entrypoint: ["sh", "-c","
        ./dockerize -wait=tcp://camunda:7777 -timeout=360s -- &&
        sh /usr/app/entrypoint.sh"]

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./monitoring/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133"  # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "1888:1888"   # pprof extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-all-in-one
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
