camunda.bpm:
  admin-user:
    id: admin
    password: pw
  filter:
    create: All tasks
  authorization:
    enabled: true
  generic-properties:
    properties:
      initialize-telemetry: false
      telemetry-reporter-activate: false

server:
  port: 7777

spring:
  jersey:
    application-path: /rest
